### ISSUE TITLE
Feature Request: Expose the pairing value

### ISSUE THREAD

**Issue by wbl** [kilic/bls12-381#5]
Currently this package only exposes a function to determine if a pairing is unity or not, but not a function to compute pairing values and no way to do arithmetic on the torus. These are needed for applications such as identity based encryption.

**Comment by kilic** [comment]
A new release is on the way and extension field functions will be exposed.

**Comment by kilic** [comment]
Target mul subgroup is now exposed and can be reached like below.

```
e := bls.NewEngine()
GT := e.GT()
```
