### ISSUE TITLE
Reciprocal for Gt?

### ISSUE THREAD

**Issue by wbl** [kilic/bls12-381#9]
In trying to implement the YAHK scheme I realized that I need a reciprocal in Gt. While it's possible to implement for elements of order r through exponent, there probably are more efficient methods.

**Comment by kilic** [comment]
Inverse is exposed with [this](https://github.com/kilic/bls12-381/commit/7b21d9e236c1badad5881a6cbc23f6689847b159). Does it works well for YAHK requirements?

And please feel free for PRs
